import type { Metadata } from "next";
import { Oswald, Poppins } from "next/font/google";
import "./globals.css";

const poppin = Poppins({
  subsets: ["latin"],
  weight: ["400", "300", "600", "500", "700"],
  variable: "--font-poppin",
});
const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "300", "600", "500", "700"],
  variable: "--font-oswald",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppin.variable} ${oswald.variable}`}>
        {children}
      </body>
    </html>
  );
}
